### ISSUE TITLE
Atrribute error in generator.py

### ISSUE THREAD

**Issue by Crepco** [ashutoshkrris/Password-Manager-using-Tkinter#1]
```py 
Traceback (most recent call last):
  File "c:\Users\HP\Documents\GitHub\Password_Manager\generator.py", line 68, in <module>
    PasswordGenerator().window.mainloop()     
  File "c:\Users\HP\Documents\GitHub\Password_Manager\generator.py", line 33, in __init__
    self.password_entry_box.pack(pady=20)
AttributeError: 'PasswordGenerator' object has no attribute 'password_entry_box'
```

Getting this error on line 32 in generator.py

**Comment by ashutoshkrris** [comment]
@Crepco 
Could you share your code (whatever you've written) for `generator.py` file here?

**Comment by Crepco** [comment]
```py
        self.passsword_entry_box = Entry(self.window, text ="",width=50)
        self.password_entry_box.pack(pady=20)
      ```

**Comment by Crepco** [comment]
> @Crepco Could you share your code (whatever you've written) for `generator.py` file here?

```py
        self.passsword_entry_box = Entry(self.window, text ="",width=50)
        self.password_entry_box.pack(pady=20)
```

its the same as in your repo

**Comment by ashutoshkrris** [comment]
You have a typo in the first line. You misspelt the word **password**.

**Comment by Crepco** [comment]
> You have a typo in the first line. You misspelt the word **password**.

i am extremely sorry for disturbing you. thank you for your help..

**Comment by ashutoshkrris** [comment]
It's okay.
Happy coding!
Do star the repository if you like it, and share it with your mates.
